import menus from "./menus";

export default [
  {
    url: "/admin/settings/site",
    id: "settings:site",
    icon: "bi bi-window-sidebar",
    title: "Site",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/blog",
    id: "settings:blog",
    icon: "bi bi-journal-richtext",
    title: "Blog",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/users",
    id: "settings:users",
    icon: "bi bi-person",
    title: "Users",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/categories",
    id: "settings:categories",
    icon: "bi bi-list-nested",
    title: "Categories",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/posts",
    id: "settings:posts",
    icon: "bi bi-card-text",
    title: "Posts",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/file-uploads",
    id: "settings:file-uploads",
    icon: "bi bi-file-earmark-arrow-up",
    title: "File Uploads",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/emails",
    id: "settings:emails",
    icon: "bi bi-mailbox",
    title: "Emails",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/notifications",
    id: "settings:notifications",
    icon: "bi bi-bell",
    title: "Notifications",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/web-and-seo",
    id: "settings:web-and-seo",
    icon: "bi bi-globe-americas",
    title: "Web Crawler & SEO",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
  {
    url: "/admin/settings/cookies",
    id: "settings:cookies",
    icon: "bi bi-cookie",
    title: "Cookies",
    classes: "",
    menu: menus.SETTINGS,
    child: [],
  },
];
